name 'apache-hardening'
maintainer 'DevSec Hardening Framework Team'
maintainer_email 'hello@dev-sec.io'
license 'Apache-2.0'
description 'Installs and configures a secure apache server'
version '1.0.0'

depends 'apache2', '~> 3.2.2'

supports 'amazon'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'debian'
supports 'ubuntu'
supports 'oracle'
